### PR TITLE
only allow to activate BLE if required fields are given

### PR DESCRIPTION
**Pull request by foxriver76**

### CODE REVIEW

**Review by Apollon77 — APPROVED** [review]

**Comment by Apollon77** [comment]
Will the wifi/thread credentials  still be saved also when ble is not activated?

**Comment by foxriver76** [comment]
> Will the wifi/thread credentials still be saved also when ble is not activated?

Currently we have no extra save button and saving on e.g. every loss of focus will lead to a lot of object changes. So do you think we need an additional save button?

**Comment by Apollon77** [comment]
ets leave it that way. I think the important thing is that the wifi/thread data stay stored if ble w?uld be disabled ... this shoukd be the case, right?

**Comment by foxriver76** [comment]
> ets leave it that way. I think the important thing is that the wifi/thread data stay stored if ble w?uld be disabled ... this shoukd be the case, right?

Yes, Frontend will also not delete any data, it will then send message to the backend with the configured data and `controller.ble` set to false.

**Comment by foxriver76** [comment]
But I will push another adaption tomorrow to this PR, to show user a more meaningful message if required props are not fulfilled.

**Review by Apollon77 — APPROVED** [review]

**Pull request merged**
